---
#-------------------------------
# General Site Settings
title: Nana Antwi
logo: logo2.svg # You can add own logo.
description: Zolan is modern minimal theme for Jekyll

#-------------------------------
# Author Settings
author:
  name: Nana Antwi
  image: nana_antwi.jpg
  say-hello: Hello, I’m <strong>Nana Antwi</strong>
  bio: I'm an incoming M.S. student in the Computer Science department at <strong>Columbia University</strong>. My currents interests are in the field of <strong>Machine Learning</strong> and <strong>Natural Language Processing</strong>. I'm currently a Software Engineering Intern at Workschool. I earned my B.S. degree in Chemistry and Chemical Biology at <strong>Cornell University</strong>. My research at Cornell broadly covered developing novel methods for delivering drug molecules. Outside Chemistry and CS, I love <strong>Music</strong>, <strong>Art</strong>, <strong>Psychology</strong>, <strong>Philosophy</strong> (Black Phenomenology).

#-------------------------------
# Contact links
twitter: http://twitter.com/AntNanaK # Add your Twitter handle
facebook: http://www.facebook.com/nanaduahantwi # Add your Facebook handle
dribbble: https://dribbble.com/ # Add your Dribbble handle
instagram: https://instagram.com/n_antwi # Add your Instagram handle
pinterest: https://pinterest.com/nanaduahantwi # Add your Pinterest handle
linkedin: http://www.linkedin.com/in/nana-antwi-956376156
github: http://github.com/Antwi007

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: n_antwi # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
